[package]
name = "weblog-example-web-sys"
version = "0.4.0-beta.1"
repository = "https://git.netflux.io/rob/weblog"
authors = ["Rob Watson"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
weblog = { path = "../.." }
wasm-bindgen = "0.2"
